# Generated by Django 3.1.5 on 2021-01-21 08:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Web Development', 'Web Development'), ('IT software', 'IT software'), ('computers', 'computers'), ('Marketing', 'Marketing'), ('Personal Development', 'Personal Development'), ('Photograpy', 'Photograpy'), ('Business', 'Business'), ('Painting', 'Painting'), ('Design', 'Design')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Course categories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_img', models.ImageField(upload_to='course/main_images/')),
                ('title', models.CharField(max_length=60)),
                ('info', models.TextField(max_length=250, validators=[django.core.validators.MinLengthValidator(100)])),
                ('d_price', models.FloatField(validators=[django.core.validators.MaxValueValidator(15000), django.core.validators.MinValueValidator(199)])),
                ('o_price', models.FloatField(validators=[django.core.validators.MaxValueValidator(15000), django.core.validators.MinValueValidator(199)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coursecategory')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
