# Generated by Django 3.1.5 on 2021-01-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='img_thumb',
            field=models.ImageField(default='!', upload_to='course/main_images/thumbs/'),
            preserve_default=False,
        ),
    ]
