# Generated by Django 3.1.5 on 2021-01-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_img_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='img_thumb',
        ),
    ]
