# Generated by Django 3.1.5 on 2021-01-20 08:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website url')),
                ('facebook', models.CharField(blank=True, max_length=50, null=True, verbose_name='facebook url')),
                ('twitter', models.CharField(blank=True, max_length=50, null=True, verbose_name='twitter url')),
                ('github', models.CharField(blank=True, max_length=50, null=True, verbose_name='github url')),
                ('linkedin', models.CharField(blank=True, max_length=50, null=True, verbose_name='linkedin url')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_headline', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='heading')),
                ('professional_info', models.TextField(blank=True, max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(100)])),
                ('profile_links', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profilelinks')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
