# Generated by Django 3.1.5 on 2021-01-20 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_links',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profilelinks'),
        ),
    ]
