# Generated by Django 3.1.5 on 2021-01-20 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210120_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_links',
        ),
        migrations.AddField(
            model_name='profilelinks',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
