# Generated by Django 3.1.5 on 2021-01-20 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210120_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilelinks',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
